apiVersion: apps/v1
kind: Deployment
metadata:
  name: quic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quic-app
  template:
    metadata:
      labels:
        app: quic-app
    spec:
      imagePullSecrets: 
      - name: docker-login
      containers:
        - name: quic-app
          image: michaelwoleary/quic-app:latest
          ports:
            - containerPort: 443
              protocol: UDP
            - containerPort: 443
              protocol: TCP

