apiVersion: v1
kind: Secret
metadata:
  name: docker-login
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImVXOTFjaTFrYjJOclpYSXRkWE5sY201aGJXVTZlVzkxY2kxa2IyTnJaWEl0Y0dGemMzZHZjbVE9IgogICAgICAgICAgICAgICAgfQogICAgICAgIH0KfQo=
type: kubernetes.io/dockerconfigjson
