apiVersion: v1
kind: Service
metadata:
  name: quic-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: quic-app
  ports:
    - name: quic
      protocol: UDP
      port: 443
      targetPort: 443
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer

